### ISSUE TITLE
Conversion : PB mapping entre colonnes quanti et colonnes identification

### ISSUE THREAD

**Issue by mariannetardif** [prostarproteomics/Prostar2#71]
Conversion 
A l'étape du choix des colonnes de quanti :  colonnes d'identification choix coche YES. Je parviens à sélectionner le groupe de colonnes de quantification (Maj-select), mais je ne parviens pas à sélectionner le groupe de colonnes d'identification, c'est toujours une seule colonne sélectionnée à la fois.

(.. si je continue malgré tout, au moment de faire Save le QFeature, la session plante)

**Comment by samWieczorek** [comment]
Leproblème se produti quand on clique sur "Yes" avant d'avoir sélectionné les données de quanti. Lorsque c'est fait, il n'y a qu'un seul champ sélectionnable pour les metadata. Prostar ne se remet pas à jour en fonction des données de quanti qui viennent d'être sélectionnées
